RESULTS_FOLDER = "results"
BALANCE = False
LR = 0.001
BATCH_SIZE = 128
EPOCHS = 50
PATIENCE = 5
DELTA = 0.001
TOP_K = 10
K = 5
SEEDS = [0, 1, 42]
TARGET_COL = "rating"
USER_COL = "user_id"
ITEM_COL = "item_id"
OUTPUT_MODEL_PATH = "model.pt"
DATASETS_CHOICES = ["mars", "itm"]
DATASET = "mars"
CV_TYPES_CHOICES = ["kfold", "loo"]
CV_TYPE = "kfold"
PLOT = False
STATS_TEST = False
